package com.example.photoquestv3.Models

object ChallengeObjects {
    val ChallengeLists = mutableListOf(
        Challenges("Take a photo of a bird in a natural setting", "2025-03-12", false),
        Challenges("Photograph litter in a public space", "2025-03-11", false),
        Challenges("Capture an animal in your local area", "2025-03-10", false),
        Challenges("Take a picture of a tree or plant in your neighborhood", "2025-03-09", false),
        Challenges("Photograph some trash in a park or beach", "2025-03-08", false),
        Challenges("Document a pet or local wildlife interacting with nature", "2025-03-07", false),
        Challenges("Take a picture of a plant growing in a small crack or unusual spot", "2025-03-06", false),
        Challenges("Photograph an animal in your yard or garden", "2025-03-05", false),
        Challenges("Capture a piece of trash in a nature setting", "2025-03-04", false),
        Challenges("Take a close-up photo of a flower or small animal", "2025-03-03", false),
        Challenges("Capture a moment of wildlife in motion", "2025-03-02", false),
        Challenges("Take a close-up photo of a tiny creature in nature", "2025-03-01", false),
        Challenges("Photograph the beauty of a neglected natural area", "2025-02-28", false),
        Challenges("Document a clean-up effort in a natural space", "2025-02-27", false),
        Challenges("Capture the contrast between nature and man-made waste", "2025-02-26", false),
        Challenges("Photograph a sunset", "2025-02-25", false),
        Challenges("Take a picture from an unusual angle", "2025-02-24", false),
        Challenges("Photograph something that symbolizes happiness", "2025-02-23", false),
        Challenges("Take a photo of something in the rain", "2025-02-22", false),
        Challenges("Photograph something in nature that is reflecting", "2025-02-21", false),
        Challenges("Take a black-and-white photo", "2025-02-20", false),
        Challenges("Take a picture of something in motion", "2025-02-19", false),
        Challenges("Photograph something old or antique", "2025-02-18", false),
        Challenges("Take a portrait of someone", "2025-02-17", false),
        Challenges("Take a picture of a reflection", "2025-02-16", false),
        Challenges("Photograph a flower up close", "2025-02-15", false),
        Challenges("Take a picture of your own shadow", "2025-02-14", false),
        Challenges("Photograph something red", "2025-02-13", false),
        Challenges("Photograph a city skyline at night", "2025-02-12", false),
        Challenges("Take a picture with a reflective object", "2025-02-11", false),
        Challenges("Photograph an animal in its natural habitat", "2025-02-10", false),
        Challenges("Photograph litter in an unexpected place", "2025-02-09", false),
        Challenges("Capture an animal in its natural habitat", "2025-02-08", false),
        Challenges("Take a photo of a plant growing in an unlikely spot", "2025-02-07", false),
        Challenges("Document the impact of pollution on a natural area", "2025-02-06", false),
        Challenges("Photograph a piece of nature reclaimed by urban space", "2025-02-05", false),

        )
}