package com.example.photoquestv3.Models

object ChallengeObjects {
    val ChallengeLists = mutableListOf(
        Challenges("Take a photo of a sunset over water", "2025-03-31", false),
        Challenges("Photograph a street artist at work", "2025-03-30", false),
        Challenges("Capture a photo of a cityscape during golden hour", "2025-03-29", false),
        Challenges("Take a picture of a reflection in a puddle or lake", "2025-03-28", false),
        Challenges("Photograph a scene that tells a story", "2025-03-27", false),
        Challenges("Capture a silhouette of someone against a bright background", "2025-03-26", false),
        Challenges("Take a close-up of an insect or small creature", "2025-03-25", false),
        Challenges("Photograph a bird in flight", "2025-03-24", false),
        Challenges("Capture a moment of laughter between two people", "2025-03-23", false),
        Challenges("Take a picture of a vibrant street market", "2025-03-22", false),
        Challenges("Photograph a moment of someone helping another person", "2025-03-21", false),
        Challenges("Capture the texture of something natural, like bark or leaves", "2025-03-20", false),
        Challenges("Take a photo of a flower in bloom", "2025-03-19", false),
        Challenges("Photograph something with contrasting colors", "2025-03-18", false),
        Challenges("Take a picture of a child playing in nature", "2025-03-17", false),
        Challenges("Photograph the texture of a rock or stone", "2025-03-16", false),
        Challenges("Capture a quiet moment in a park", "2025-03-15", false),
        Challenges("Take a photo of a local landmark", "2025-03-14", false),
        Challenges("Photograph a cool person", "2025-03-13", false),
        Challenges("Take a photo of a bird in a natural setting", "2025-03-12", false),
        Challenges("Photograph litter in a public space", "2025-03-11", false),
        Challenges("Capture an animal in your local area", "2025-03-10", false),
        Challenges("Take a picture of a tree or plant in your neighborhood", "2025-03-09", false),
        Challenges("Photograph some trash in a park or beach", "2025-03-08", false),
        Challenges("Document a pet or local wildlife interacting with nature", "2025-03-07", false),
        Challenges("Take a picture of a plant growing in a small crack or unusual spot", "2025-03-06", false),
        Challenges("Photograph an animal in your yard or garden", "2025-03-05", false),
        Challenges("Capture a piece of trash in a nature setting", "2025-03-04", false),
        Challenges("Take a close-up photo of a flower or small animal", "2025-03-03", false),
        Challenges("Capture a moment of wildlife in motion", "2025-03-02", false),
        Challenges("Take a close-up photo of a tiny creature in nature", "2025-03-01", false),
        Challenges("Photograph the beauty of a neglected natural area", "2025-02-28", false),
        Challenges("Document a clean-up effort in a natural space", "2025-02-27", false),
        Challenges("Capture the contrast between nature and man-made waste", "2025-02-26", false),
        Challenges("Photograph a sunset", "2025-02-25", false),
        Challenges("Take a picture from an unusual angle", "2025-02-24", false),
        Challenges("Photograph something that symbolizes happiness", "2025-02-23", false),
        Challenges("Take a photo of something in the rain", "2025-02-22", false),
        Challenges("Photograph something in nature that is reflecting", "2025-02-21", false),
        Challenges("Take a black-and-white photo", "2025-02-20", false),
        Challenges("Take a picture of something in motion", "2025-02-19", false),
        Challenges("Photograph something old or antique", "2025-02-18", false),
        Challenges("Take a portrait of someone", "2025-02-17", false),
        )
}