name: Android CI Build Test

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle



      - name: Create google-services.json
        run: echo '${{secrets.GOOGLE_SERVICES_JSON}}' > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check dependencies
        run: ./gradlew dependencies

      - name: Build with Gradle
        run: ./gradlew build