name: Build Test
on:
  push:
    branches: [master]

  pull_request:
     branches: [master]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4
      - name: setup JDK
        uses: actions/setup-java@4
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle



      - name: Create google-services-json
        uses: echo '${{KEY}}' > app/google-services.json

      - name: Gradle permission
        run: chmod +x gradlew

      - name: check dependencies
        run: ./gradlew dependencies

      - name: Build Gradle
        run: ./gradlew build

